feat(matrix/space): implemented `space.board` events
commune-os/commune-rs pull request #16
Opened 2024-01-26 17:27 UTC by avdb13

Stumbled upon some difficulties here since I wanted to do stuff correct without changing the API later.
I chose to separate `post` from `reply` to prevent having a separate `topic` event. Votes for `reply` are calculated through `m.reaction` but since it can form a relation with any event we can't enforce votes on this event type only.
I was not sure if we needed an enum for `post` since we might consider having different `body` types in the future such as a poll or media content.

2024-01-28 21:08 UTC, EstebanBorai commented on crates/core/src/db/entities/legacy.rs
Perhaps this belongs to Matrix layer?

2024-01-28 21:08 UTC, EstebanBorai commented on crates/core/src/events/service.rs
> +        ";
Is there a way to achieve this via API? I would rather avoid querying database directly.

2024-01-28 21:08 UTC, EstebanBorai commented on crates/core/src/events/service.rs
> +    }
Please avoid committing unimplemented functions.

2024-01-28 21:08 UTC, EstebanBorai commented on crates/core/src/lib.rs
> +pub mod db;
Direct database access is not encouraged, unless core contains an owned DB I suggest using the Synapse API.

2024-01-29 22:05 UTC, avdb13 commented on crates/core/src/db/entities/legacy.rs
My bad, I see now that I didn't think about the design well. We should be able to handle DTOs in the old format but entities shouldnt since I dont expect anyone to keep the old DB around.

2024-01-29 22:09 UTC, avdb13 commented on crates/core/src/events/service.rs
> +        ";
This is possible for Matrix events but our problem is that the response is paginated (see below).
I also decided to avoid plain SQL and go with `sea_query` instead as we wanna support SQLite and RocksDB in the future.
https://matrix-org.github.io/synapse/latest/admin_api/rooms.html

2024-01-29 22:11 UTC, avdb13 commented on crates/core/src/lib.rs
> +pub mod db;
It is not encouraged but it should be fine as long as we check Synapse's database schema, only perform reads and avoid views where possible.

2024-02-02 22:37 UTC, avdb13 commented
Excuses for not writing any tests yet by the way!

2024-02-03 02:48 UTC, EstebanBorai commented on crates/core/src/events/service.rs
> +        ";
I think we can use filters and search terms for this perhaps?

2024-02-03 02:48 UTC, EstebanBorai commented on crates/core/src/lib.rs
> +pub mod db;
I would use SQL Read Ops as last resort, its safer to use API as DAL.

2024-02-03 02:50 UTC, EstebanBorai commented on Cargo.toml
> +assert_matches2 = "0.1.2"
Why is this required?

2024-02-03 02:51 UTC, EstebanBorai commented on crates/core/src/events/service.rs
> +    }
Please specify error cause. Context is defined in the API

2024-02-03 02:52 UTC, EstebanBorai commented on crates/core/src/events/service.rs
> +        board_id: S,
```suggestion
        board_id: impl AsRef<str>,
```

Given that this is the single param that uses generic value

2024-02-03 03:06 UTC, EstebanBorai requested changes
Thanks for giving this a shot!
I see this PR involves many features all at once in different layers of abstraction. I suggest split it into different PRs to address each concern at its own level.

I suggest using API calls over DB conns for DAL as well.

And please add tests, its important code is validated and that we can ensure it doesn't breaks with future changes!

I can see theres many types of events addressed all at once, perhaps adding the event abstraction to matrix crate is a good start for a PR, then introduce one of the event types and finally introduce it to the core logic so its presented (this could be a second PR) at this point testing against matrix and core logic its easy (refer to test crate for examples).

Keep it up!!

2024-02-05 10:30 UTC, avdb13 commented on Cargo.toml
> +assert_matches2 = "0.1.2"
This is used for tests.
See: https://docs.rs/assert_matches2/latest/assert_matches2

2024-02-05 10:30 UTC, avdb13 commented on crates/core/src/lib.rs
> +pub mod db;
No direct database should be happening.

2024-02-05 10:36 UTC, avdb13 commented on crates/core/src/events/service.rs
> +    }
Could you elaborate on context? The first error can only happen when the token is of the wrong format or empty, while the second one can be related to a wrong access token or malformed body.
Returning `Error::Unknown` here is not ideal, is that what you want to be changed?

2024-02-05 10:37 UTC, avdb13 commented on crates/matrix/src/client/resources/events.rs
> +
?

2024-02-05 15:44 UTC, avdb13 commented on crates/server/src/router/api/v1/events/legacy/mod.rs
I already explained this ... it was to keep backward compatibility. Seems like it doesn't matter since it's only making implementation harder than necessary.

2024-02-05 17:12 UTC, closed without merging